---
- name: Update apt packages, reboot if required and install gui dependencies
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: "yes"
        update_cache: true

    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot if required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true

    - name: Install desktop environment
      ansible.builtin.apt:
        install_recommends: false
        pkg:
          - xauth
          - build-essential
          - virtualbox-guest-utils
          - virtualbox-guest-x11
