- name: Install VLC and vlc-plugin-base
  hosts: all
  become: yes
  tasks:
    - name: Install VLC and vlc-plugin-base
      apt:
        name:
          - vlc
          - vlc-plugin-base
        state: present
    - name: Create non-root user "vlc"
      user:
        name: vlc
        state: present
        shell: /bin/bash
        createhome: yes
