---
- name: Install Wireshark
  hosts: all
  become: true
  tasks:
    - name: Configure Wireshark for all users
      ansible.builtin.shell:
        cmd: echo "wireshark-common wireshark-common/install-setuid boolean true" | sudo debconf-set-selections

    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: "yes"
        update_cache: true

    - name: Install dependencies
      ansible.builtin.apt:
        pkg:
          - wireshark
          - net-tools
          - bwm-ng
          - tcpreplay
          - hping3

    - name: Add user to wireshark group
      ansible.builtin.user:
        name: vagrant
        groups: wireshark
        append: yes

    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file
    - name: Reboot if required
      ansible.builtin.reboot:
      when: reboot_required_file.stat.exists == true
